language: go

dist: bionic
sudo: required

go:
  # Test Go versions 1.13 and the most recent. Assume that in-between also works!
  - 1.13.x  # This should stay at 1.13, as gonum supports only 1.13+
  - 1.15.x  # This should track the lastest Go release (1.15 came out 10 Aug 2020)

go_import_path: github.com/usnistgov/dastard

script:
  - go test -v ./...

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_18.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_18.04/Release.key'
    packages:
    - libczmq-dev libzmq3-dev libsodium-dev
