language: go

dist: xenial
sudo: required

go:
  - 1.10.x

go_import_path: github.com/usnistgov/dastard

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/Release.key'
    packages:
    - libczmq-dev libzmq3-dev

cache:
  apt: true
  directories:
  - $HOME/libsodium

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib
