language: go

go:
  - 1.8
  - 1.9.x

go_import_path: github.com/usnistgov/dastard

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y   # for libsodium
  - sudo add-apt-repository ppa:kevinkreiser/czmq -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev libzmq3 libzmq3-dev
  - sudo apt-get libczmq-dev  libczmq czmq
